### ISSUE TITLE
[Improvement] ShuffleServerGrpcNettyClient  sendShuffleData support config maxRetryAttempts 

### ISSUE THREAD

**Issue by xumanbu** [apache/incubator-uniffle#1175]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

I encountered an error while using the Netty client with the configuration.
```
spark.rss.client.type = GRPC_NETTY
spark.rss.client.retry.max = 50
spark.rss.client.retry.interval.max = 20000
```
But actually, attempt three times in total.

I noticed that the current code only initializes GrpcClient.maxRetryAttempts to a value of 3.

```
23/08/25 18:58:41 WARN [netty-rpc-client-28-2] TransportChannelHandler: Exception in connection from /10.xxx.xx.xx:49999
org.apache.uniffle.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3103784960, max: 3113877504)
	at org.apache.uniffle.io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:802)
	at org.apache.uniffle.io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:731)
	at org.apache.uniffle.io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:632)
	at org.apache.uniffle.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:607)
	at org.apache.uniffle.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:202)
	at org.apache.uniffle.io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:172)
	at org.apache.uniffle.io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
	at org.apache.uniffle.io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
	at org.apache.uniffle.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
	at org.apache.uniffle.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at org.apache.uniffle.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at org.apache.uniffle.io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:140)
	at org.apache.uniffle.io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at org.apache.uniffle.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:150)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at org.apache.uniffle.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at org.apache.uniffle.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.uniffle.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
23/08/25 18:58:41 WARN [netty-rpc-client-28-2] AbstractChannelHandlerContext: An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
org.apache.uniffle.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3103784960, max: 3113877504)
	at org.apache.uniffle.io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:802)
	at org.apache.uniffle.io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:731)
	at org.apache.uniffle.io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:632)
	at org.apache.uniffle.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:607)
	at org.apache.uniffle.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:202)
	at org.apache.uniffle.io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:172)
	at org.apache.uniffle.io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
	at org.apache.uniffle.io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
	at org.apache.uniffle.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
	at org.apache.uniffle.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at org.apache.uniffle.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at org.apache.uniffle.io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:140)
	at org.apache.uniffle.io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at org.apache.uniffle.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:150)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at org.apache.uniffle.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at org.apache.uniffle.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.uniffle.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
23/08/25 18:58:41 ERROR [netty-rpc-client-28-2] TransportResponseHandler: Still have 1 requests outstanding when connection from /10.155.96.22:49999 is closed
23/08/25 18:58:41 INFO [pool-6-thread-2] RetryUtils: Retry due to Throwable, org.apache.uniffle.common.exception.RssException java.util.concurrent.ExecutionException: java.io.IOException: Connection from /10.xx.xxx.xx::49999 closed
23/08/25 18:58:41 INFO [pool-6-thread-2] RetryUtils: Waiting 20000 milliseconds before next connection attempt.
23/08/25 18:58:41 INFO [Executor task launch worker for task 1137] ReaderImpl: Reading ORC rows from hdfs://bipxxx05/bip/developer/xx/xxxx/dt=20230825/hm=0030/part-00007-db96623e-a56e-44a4-910c-1d4ad23039e7.c000.snappy.orc with {include: null, offset: 0, length: 41968866, sarg: leaf-0 = (IS_NULL page_type), leaf-1 = (EQUALS page_type page_commodity_detail), leaf-2 = (IS_NULL goods_id), leaf-3 = (EQUALS goods_id -99), leaf-4 = (EQUALS goods_id -999999), expr = (and (not leaf-0) leaf-1 (not leaf-2) (not leaf-3) (not leaf-4)), schema: struct<mid:string,page_type:string,goods_id:bigint,dt:string,hm:string>, includeAcidColumns: true}
23/08/25 18:58:41 WARN [netty-rpc-client-99-2] TransportChannelHandler: Exception in connection from /10.xx.xxx.xx:49999
org.apache.uniffle.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3103784960, max: 3113877504)
	at org.apache.uniffle.io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:802)
	at org.apache.uniffle.io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:731)
	at org.apache.uniffle.io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:632)
	at org.apache.uniffle.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:607)
	at org.apache.uniffle.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:202)
	at org.apache.uniffle.io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:172)
	at org.apache.uniffle.io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
	at org.apache.uniffle.io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
	at org.apache.uniffle.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
	at org.apache.uniffle.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at org.apache.uniffle.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at org.apache.uniffle.io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:140)
	at org.apache.uniffle.io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at org.apache.uniffle.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:150)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at org.apache.uniffle.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at org.apache.uniffle.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.uniffle.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
23/08/25 18:58:41 WARN [netty-rpc-client-99-2] AbstractChannelHandlerContext: An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
org.apache.uniffle.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3103784960, max: 3113877504)
	at org.apache.uniffle.io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:802)
	at org.apache.uniffle.io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:731)
	at org.apache.uniffle.io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:632)
	at org.apache.uniffle.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:607)
	at org.apache.uniffle.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:202)
	at org.apache.uniffle.io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:172)
	at org.apache.uniffle.io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
	at org.apache.uniffle.io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
	at org.apache.uniffle.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
	at org.apache.uniffle.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at org.apache.uniffle.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at org.apache.uniffle.io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:140)
	at org.apache.uniffle.io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at org.apache.uniffle.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:150)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at org.apache.uniffle.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at org.apache.uniffle.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at org.apache.uniffle.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.uniffle.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
23/08/25 18:58:41 ERROR [netty-rpc-client-99-2] TransportResponseHandler: Still have 1 requests outstanding when connection from /10.155.93.22:49999 is closed
23/08/25 18:58:41 INFO [pool-6-thread-5] RetryUtils: Retry due to Throwable, org.apache.uniffle.common.exception.RssException java.util.concurrent.ExecutionException: java.io.IOException: Connection from /10.xx.xxx.xx:49999 closed
23/08/25 18:58:41 INFO [pool-6-thread-5] RetryUtils: Waiting 20000 milliseconds before next connection attempt.
23/08/25 18:58:41 WARN [netty-rpc-client-37-2] TransportClient: Failed to send request RPC 1157 to /10.xx.xxx.xx::49999: org.apache.uniffle.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3103784960, max: 3113877504), channel will be closed
23/08/25 18:58:41 INFO [pool-6-thread-4] RetryUtils: Retry due to Throwable, org.apache.uniffle.common.exception.RssException java.util.concurrent.ExecutionException: java.io.IOException: Failed to send request RPC 1157 to /10.xx.xxx.xx::49999: org.apache.uniffle.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3103784960, max: 3113877504), channel will be closed
23/08/25 18:58:41 INFO [pool-6-thread-4] RetryUtils: Waiting 20000 milliseconds before next connection attempt.
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xumanbu** [comment]
another issue arises when sending data via netty and encounters an exception, the channel will be closed. 
but  use the closed transportClient in next retry, so retry execution will throw exception like this:
however, in the next retry, the closed transportclient will still be used. 
As a result, the execution of the retry will throw an exception similar to this:
```
23/08/25 18:59:01 WARN [netty-rpc-client-28-2] TransportClient: Failed to send request RPC 1281 to /10.155.96.22:49999: org.apache.uniffle.io.netty.channel.StacklessClosedChannelException, channel will be closed
23/08/25 18:59:01 INFO [pool-6-thread-2] RetryUtils: Retry due to Throwable, org.apache.uniffle.common.exception.RssException java.util.concurrent.ExecutionException: java.io.IOException: Failed to send request RPC 1281 to /10.XXX.XX.XX:49999: org.apache.uniffle.io.netty.channel.StacklessClosedChannelException, channel will be closed
```

**Comment by jerqi** [comment]
> another issue arises when sending data via netty and encounters an exception, the channel will be closed. but use the closed transportClient in next retry, so retry execution will throw exception like this: however, in the next retry, the closed transportclient will still be used. As a result, the execution of the retry will throw an exception similar to this:
> 
> ```
> 23/08/25 18:59:01 WARN [netty-rpc-client-28-2] TransportClient: Failed to send request RPC 1281 to /10.155.96.22:49999: org.apache.uniffle.io.netty.channel.StacklessClosedChannelException, channel will be closed
> 23/08/25 18:59:01 INFO [pool-6-thread-2] RetryUtils: Retry due to Throwable, org.apache.uniffle.common.exception.RssException java.util.concurrent.ExecutionException: java.io.IOException: Failed to send request RPC 1281 to /10.XXX.XX.XX:49999: org.apache.uniffle.io.netty.channel.StacklessClosedChannelException, channel will be closed
> ```

Does the Spark have similar issues? What's the Spark's solution?

**Comment by xumanbu** [comment]
> > another issue arises when sending data via netty and encounters an exception, the channel will be closed.  however, in the next retry, the closed transportclient will still be used. As a result, the execution of the retry will throw an exception similar to this:
> > ```
> > 23/08/25 18:59:01 WARN [netty-rpc-client-28-2] TransportClient: Failed to send request RPC 1281 to /10.155.96.22:49999: org.apache.uniffle.io.netty.channel.StacklessClosedChannelException, channel will be closed
> > 23/08/25 18:59:01 INFO [pool-6-thread-2] RetryUtils: Retry due to Throwable, org.apache.uniffle.common.exception.RssException java.util.concurrent.ExecutionException: java.io.IOException: Failed to send request RPC 1281 to /10.XXX.XX.XX:49999: org.apache.uniffle.io.netty.channel.StacklessClosedChannelException, channel will be closed
> > ```
> 
> Does the Spark have similar issues? What's the Spark's solution?

I think It's a bug.

```
// shouldn't get transportClient  outside
TransportClient transportClient = getTransportClient();
RetryUtils.retry(
            () -> {
              // should get transportClient in RetryCmd function, spark also use transportClient like this.
             //  getTransportClient() could automatically remove invalid client
              TransportClient transportClient = getTransportClient();
    })
```

In spark some retry method get transportClient in

**Comment by jerqi** [comment]
@leixm WDYT?

**Comment by jerqi** [comment]
> > > another issue arises when sending data via netty and encounters an exception, the channel will be closed.  however, in the next retry, the closed transportclient will still be used. As a result, the execution of the retry will throw an exception similar to this:
> > > ```
> > > 23/08/25 18:59:01 WARN [netty-rpc-client-28-2] TransportClient: Failed to send request RPC 1281 to /10.155.96.22:49999: org.apache.uniffle.io.netty.channel.StacklessClosedChannelException, channel will be closed
> > > 23/08/25 18:59:01 INFO [pool-6-thread-2] RetryUtils: Retry due to Throwable, org.apache.uniffle.common.exception.RssException java.util.concurrent.ExecutionException: java.io.IOException: Failed to send request RPC 1281 to /10.XXX.XX.XX:49999: org.apache.uniffle.io.netty.channel.StacklessClosedChannelException, channel will be closed
> > > ```
> > 
> > 
> > Does the Spark have similar issues? What's the Spark's solution?
> 
> I think It's a bug.
> 
> ```
> // shouldn't get transportClient  outside
> TransportClient transportClient = getTransportClient();
> RetryUtils.retry(
>             () -> {
>               // should get transportClient in RetryCmd function, spark also use transportClient like this.
>              //  getTransportClient() could automatically remove invalid client
>               TransportClient transportClient = getTransportClient();
>     })
> ```

Could you paste the related code of Spark?

**Comment by jerqi** [comment]
> > > another issue arises when sending data via netty and encounters an exception, the channel will be closed.  however, in the next retry, the closed transportclient will still be used. As a result, the execution of the retry will throw an exception similar to this:
> > > ```
> > > 23/08/25 18:59:01 WARN [netty-rpc-client-28-2] TransportClient: Failed to send request RPC 1281 to /10.155.96.22:49999: org.apache.uniffle.io.netty.channel.StacklessClosedChannelException, channel will be closed
> > > 23/08/25 18:59:01 INFO [pool-6-thread-2] RetryUtils: Retry due to Throwable, org.apache.uniffle.common.exception.RssException java.util.concurrent.ExecutionException: java.io.IOException: Failed to send request RPC 1281 to /10.XXX.XX.XX:49999: org.apache.uniffle.io.netty.channel.StacklessClosedChannelException, channel will be closed
> > > ```
> > 
> > 
> > Does the Spark have similar issues? What's the Spark's solution?
> 
> I think It's a bug.
> 
> ```
> // shouldn't get transportClient  outside
> TransportClient transportClient = getTransportClient();
> RetryUtils.retry(
>             () -> {
>               // should get transportClient in RetryCmd function, spark also use transportClient like this.
>              //  getTransportClient() could automatically remove invalid client
>               TransportClient transportClient = getTransportClient();
>     })
> ```

Make sense. Could you create a pr for this issue?
