### ISSUE TITLE
[Flaky Test] WriteAndReadMetricsTest

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#1219]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
[INFO] Running org.apache.uniffle.test.WriteAndReadMetricsTest
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 31.023 s <<< FAILURE! - in org.apache.uniffle.test.WriteAndReadMetricsTest
Error:  test  Time elapsed: 28.209 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <55> but was: <54>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at org.apache.uniffle.test.SparkIntegrationTestBase.verifyTestResult(SparkIntegrationTestBase.java:128)
	at org.apache.uniffle.test.SparkIntegrationTestBase.run(SparkIntegrationTestBase.java:67)
	at org.apache.uniffle.test.WriteAndReadMetricsTest.test(WriteAndReadMetricsTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/6311740658/job/17136352841?pr=1218

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
fix by #1235
