### ISSUE TITLE
[Bug] java.lang.NoClassDefFoundError: org/apache/uniffle/guava/util/concurrent/internal/InternalFutureFailureAccess

### ISSUE THREAD

**Issue by leixm** [apache/incubator-uniffle#1319]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When the registerShuffle interface of ShuffleServer is called, java.lang.NoClassDefFoundError will be thrown.
And I noticed that the jar package `shuffle-server-0.9.0-SNAPSHOT.jar` does not contain the class org/apache/uniffle/guava/util/concurrent/internal/InternalFutureFailureAccess. The reason is server/pom.xml line161`com. google.guava:guava`, the shaded guava package is configured. When I add these two lines of configuration, the above exception no longer occurs`<include>com.google.guava:failureaccess</include>
                  <include>com.google.guava:listenablefuture</include>`

### Affects Version(s)

master

### Uniffle Server Log Output

```logtalk
Exception in thread "Grpc-1" java.lang.NoClassDefFoundError: org/apache/uniffle/guava/util/concurrent/internal/InternalFutureFailureAccess
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.uniffle.guava.cache.LocalCache$LoadingValueReference.<init>(LocalCache.java:3476)
        at org.apache.uniffle.guava.cache.LocalCache$LoadingValueReference.<init>(LocalCache.java:3480)
        at org.apache.uniffle.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2138)
        at org.apache.uniffle.guava.cache.LocalCache$Segment.get(LocalCache.java:2049)
        at org.apache.uniffle.guava.cache.LocalCache.get(LocalCache.java:3966)
        at org.apache.uniffle.guava.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
        at org.apache.uniffle.server.ShuffleTaskManager.getAppLock(ShuffleTaskManager.java:200)
        at org.apache.uniffle.server.ShuffleTaskManager.registerShuffle(ShuffleTaskManager.java:233)
        at org.apache.uniffle.server.ShuffleServerGrpcService.registerShuffle(ShuffleServerGrpcService.java:163)
        at org.apache.uniffle.proto.ShuffleServerGrpc$MethodHandlers.invoke(ShuffleServerGrpc.java:1033)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:352)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.uniffle.guava.util.concurrent.internal.InternalFutureFailureAccess
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 56 more


Exception in thread "Grpc-9" java.lang.NoClassDefFoundError: org/apache/uniffle/guava/util/concurrent/SettableFuture
        at org.apache.uniffle.guava.cache.LocalCache$LoadingValueReference.<init>(LocalCache.java:3476)
        at org.apache.uniffle.guava.cache.LocalCache$LoadingValueReference.<init>(LocalCache.java:3480)
        at org.apache.uniffle.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2138)
        at org.apache.uniffle.guava.cache.LocalCache$Segment.get(LocalCache.java:2049)
        at org.apache.uniffle.guava.cache.LocalCache.get(LocalCache.java:3966)
        at org.apache.uniffle.guava.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
        at org.apache.uniffle.server.ShuffleTaskManager.getAppLock(ShuffleTaskManager.java:200)
        at org.apache.uniffle.server.ShuffleTaskManager.registerShuffle(ShuffleTaskManager.java:233)
        at org.apache.uniffle.server.ShuffleServerGrpcService.registerShuffle(ShuffleServerGrpcService.java:163)
        at org.apache.uniffle.proto.ShuffleServerGrpc$MethodHandlers.invoke(ShuffleServerGrpc.java:1033)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:352)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by leixm** [comment]
@zuston  PTAL.

**Comment by leixm** [comment]
It looks like shaded is missing some configuration. cc @zuston

**Comment by zuston** [comment]
I haven't checked this. Can you submit your fix ?

**Comment by leixm** [comment]
This is a Good-First issue. Some people have also reported it in the WeChat group. I will try to encourage new people to submit PR first.

**Comment by zuston** [comment]
Could you help fix this? I think this is a serious problem. @leixm
