### ISSUE TITLE
[Bug] IllegalReferenceCountException in Shuffle Server

### ISSUE THREAD

**Issue by rickyma** [apache/incubator-uniffle#1477]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

[2024-01-24 00:38:19.554] [Grpc-973] [ERROR] ShuffleServerGrpcService.sendShuffleData - Error happened when shuffleEngine.write for appId[application_1703049085550_2397150_1706027594091], shuffleId[0], partitionId[32790], statusCode=NO_REGISTER
[2024-01-24 00:38:20.996] [LocalFileFlushEventThreadPool-4] [WARN] SingleStorageManager.write - Exception happened when write data for ShuffleDataFlushEvent: eventId=14051, appId=application_1703049085550_2397150_1706027594091, shuffleId=0, startPartition=12408, endPartition=12408, retryTimes=0, underStorage=LocalStorage, isPended=false, ownedByHugePartition=false, try again
io.netty.util.IllegalReferenceCountException: refCnt: 0
        at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1440)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:895)
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:903)
        at org.apache.uniffle.common.util.ByteBufUtils.readBytes(ByteBufUtils.java:85)
        at org.apache.uniffle.storage.handler.impl.LocalFileWriteHandler.write(LocalFileWriteHandler.java:106)
        at org.apache.uniffle.server.storage.SingleStorageManager.write(SingleStorageManager.java:59)
        at org.apache.uniffle.server.storage.HybridStorageManager.write(HybridStorageManager.java:143)
        at org.apache.uniffle.server.ShuffleFlushManager.processFlushEvent(ShuffleFlushManager.java:164)
        at org.apache.uniffle.server.DefaultFlushEventHandler.handleEventAndUpdateMetrics(DefaultFlushEventHandler.java:87)
        at org.apache.uniffle.server.DefaultFlushEventHandler.lambda$dispatchEvent$0(DefaultFlushEventHandler.java:198)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
[2024-01-24 00:38:21.021] [LocalFileFlushEventThreadPool-2] [WARN] SingleStorageManager.write - Exception happened when write data for ShuffleDataFlushEvent: eventId=14052, appId=application_1703049085550_2397150_1706027594091, shuffleId=0, startPartition=12409, endPartition=12409, retryTimes=0, underStorage=LocalStorage, isPended=false, ownedByHugePartition=false, try again
io.netty.util.IllegalReferenceCountException: refCnt: 0
        at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1440)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:895)
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:903)
        at org.apache.uniffle.common.util.ByteBufUtils.readBytes(ByteBufUtils.java:85)
        at org.apache.uniffle.storage.handler.impl.LocalFileWriteHandler.write(LocalFileWriteHandler.java:106)
        at org.apache.uniffle.server.storage.SingleStorageManager.write(SingleStorageManager.java:59)
        at org.apache.uniffle.server.storage.HybridStorageManager.write(HybridStorageManager.java:143)
        at org.apache.uniffle.server.ShuffleFlushManager.processFlushEvent(ShuffleFlushManager.java:164)
        at org.apache.uniffle.server.DefaultFlushEventHandler.handleEventAndUpdateMetrics(DefaultFlushEventHandler.java:87)
        at org.apache.uniffle.server.DefaultFlushEventHandler.lambda$dispatchEvent$0(DefaultFlushEventHandler.java:198)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
@zuston PTAL. Not sure if this is related to #1461

**Comment by zuston** [comment]
> @zuston PTAL. Not sure if this is related to #1461

Not sure.

**Comment by rickyma** [comment]
Didn't reproduce it, closed. Maybe it has been fixed already.

**Comment by dingshun3016** [comment]
I also found this case
`[WARN] 2024-05-14 08:14:18,357 LocalFileFlushEventThreadPool-36 SingleStorageManager write - Exception happened when write data for ShuffleDataFlushEvent: eventId=12568330,
appId=application_1715067054210_414115_-779157491-95513, shuffleId=0, startPartition=55, endPartition=55, retryTimes=0, underStorage=LocalStorage, isPended=false, try again
io.netty.util.IllegalReferenceCountException: refCnt: 0
        at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1440)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
        at io.netty.buffer.UnpooledDirectByteBuf.readBytes(UnpooledDirectByteBuf.java:316)
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:903)
        at org.apache.uniffle.common.util.ByteBufUtils.readBytes(ByteBufUtils.java:79)
        at org.apache.uniffle.storage.handler.impl.LocalFileWriteHandler.write(LocalFileWriteHandler.java:106)
        at org.apache.uniffle.server.storage.SingleStorageManager.write(SingleStorageManager.java:59)
        at org.apache.uniffle.server.storage.HybridStorageManager.write(HybridStorageManager.java:151)
        at org.apache.uniffle.server.ShuffleFlushManager.flushToFile(ShuffleFlushManager.java:210)
        at org.apache.uniffle.server.ShuffleFlushManager.processEvent(ShuffleFlushManager.java:91)
        at org.apache.uniffle.server.DefaultFlushEventHandler.handleEventAndUpdateMetrics(DefaultFlushEventHandler.java:76)
        at org.apache.uniffle.server.DefaultFlushEventHandler.lambda$processNextEvent$1(DefaultFlushEventHandler.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by rickyma** [comment]
Are you using the latest code? I've never reproduced it.

**Comment by dingshun3016** [comment]
The code I use is checkout from the master branch, at that time, the latest commit of the master branch was `upgrade to 0.9.0-snapshot (#1176)`.  The code behind is the code I cherry pick from the master branch or customized as needed. 
Do you know what subsequent commits will help this problem?

**Comment by dingshun3016** [comment]
> Are you using the latest code? I've never reproduced it.

The code I use is checkout from the master branch, at that time, the latest commit of the master branch was `upgrade to 0.9.0-snapshot (#1176)`. The code behind is the code I cherry pick from the master branch or customized as needed.
Do you know what subsequent commits will help this problem?

**Comment by dingshun3016** [comment]
On my side, this case only occurred once after the cluster has been running for a long time.

**Comment by rickyma** [comment]
Have you tried https://github.com/apache/incubator-uniffle/pull/1574? Maybe it will help you. The buffer could already be released by other cleaner threads after it has already been put into the flushing queue.

**Comment by dingshun3016** [comment]
> Have you tried #1574? Maybe it will help you. The buffer could've been released by other cleaner threads after it has already been put into the flushing queue.

Thanks, I'll take a look
