### ISSUE TITLE
[Bug] Unexpected exceptions happened when flushing events

### ISSUE THREAD

**Issue by rickyma** [apache/incubator-uniffle#1542]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

As described in https://github.com/apache/incubator-uniffle/pull/1537, here is the full stack trace:

```
[2024-02-24 21:01:20.540] [checkResource-0] [WARN] ShuffleTaskManager.preAllocatedBufferCheck - Remove expired preAllocatedBuffer[id=1213266] that required by app: application_1703049085550_4925739_1708775782306
[2024-02-24 21:01:20.540] [expiredAppCleaner-0] [INFO] ShuffleTaskManager.checkResourceStatus - Detect expired appId[application_1703049085550_4925739_1708775782306] according to rss.server.app.expired.withoutHeartbeat
[2024-02-24 21:01:20.547] [clearResourceThread] [INFO] ShuffleTaskManager.removeResources - Start remove resource for appId[application_1703049085550_4925739_1708775782306]
[2024-02-24 21:01:21.078] [LocalFileFlushEventThreadPool-0] [ERROR] DefaultFlushEventHandler.handleEventAndUpdateMetrics - Unexpected exceptions happened due to
java.lang.NullPointerException
at org.apache.uniffle.server.ShuffleTaskInfo.getMaxConcurrencyPerPartitionToWrite(ShuffleTaskInfo.java:109)
at org.apache.uniffle.server.ShuffleFlushManager.getMaxConcurrencyPerPartitionWrite(ShuffleFlushManager.java:198)
at org.apache.uniffle.server.ShuffleFlushManager.processFlushEvent(ShuffleFlushManager.java:149)
at org.apache.uniffle.server.DefaultFlushEventHandler.handleEventAndUpdateMetrics(DefaultFlushEventHandler.java:87)
at org.apache.uniffle.server.DefaultFlushEventHandler.lambda$dispatchEvent$0(DefaultFlushEventHandler.java:203)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
```

As you can see, the exception will happen right after the appId is expired and the resources related to the appId are removed.

NPE happend here:
```
public int getMaxConcurrencyPerPartitionToWrite() {
  return specification.get().getMaxConcurrencyPerPartitionToWrite();
}
```

I wanna discuss about it. What's the best way to avoid the exception?

Updated:
I've encountered another exception too:
```
[2024-03-08 17:50:24.075] [epollEventLoopGroup-3-95] [ERROR] ShuffleServerNettyHandler.handleSendShuffleDataRequest - Error happened when shuffleEngine.write for appId[application_1703049085550_5931482_1709891324515], shuffleId[0], partitionId[18632]: null
java.lang.NullPointerException
        at org.apache.uniffle.server.ShuffleTaskManager.getDataDistributionType(ShuffleTaskManager.java:861)
        at org.apache.uniffle.server.ShuffleFlushManager.getDataDistributionType(ShuffleFlushManager.java:270)
        at org.apache.uniffle.server.buffer.ShuffleBufferManager.flushBuffer(ShuffleBufferManager.java:301)
        at org.apache.uniffle.server.buffer.ShuffleBufferManager.flush(ShuffleBufferManager.java:468)
        at org.apache.uniffle.server.buffer.ShuffleBufferManager.flushIfNecessary(ShuffleBufferManager.java:268)
        at org.apache.uniffle.server.buffer.ShuffleBufferManager.cacheShuffleData(ShuffleBufferManager.java:187)
        at org.apache.uniffle.server.ShuffleTaskManager.cacheShuffleData(ShuffleTaskManager.java:302)
        at org.apache.uniffle.server.netty.ShuffleServerNettyHandler.handleSendShuffleDataRequest(ShuffleServerNettyHandler.java:168)
        at org.apache.uniffle.server.netty.ShuffleServerNettyHandler.receive(ShuffleServerNettyHandler.java:78)
        at org.apache.uniffle.common.netty.handle.TransportRequestHandler.handle(TransportRequestHandler.java:62)
        at org.apache.uniffle.common.netty.handle.TransportChannelHandler.channelRead(TransportChannelHandler.java:100)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at org.apache.uniffle.common.netty.TransportFrameDecoder.channelRead(TransportFrameDecoder.java:80)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
Anyone will be welcome to pick this up.

**Comment by rickyma** [comment]
Done by https://github.com/apache/incubator-uniffle/pull/1574
