### ISSUE TITLE
[Bug] A concurrency issue occurred when flushing events and removing resources at the same time

### ISSUE THREAD

**Issue by rickyma** [apache/incubator-uniffle#1560]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```
[2024-03-05 12:24:37.811] [clearResourceThread] [ERROR] ShuffleTaskManager.lambda$new$0 - Exception happened when clearing resource for expired application for appId: application_1703049085550_5682506_1709610574306
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
        at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148)
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
        at org.apache.uniffle.server.buffer.ShuffleBufferManager.lambda$removeBufferByShuffleId$9(ShuffleBufferManager.java:656)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.apache.uniffle.server.buffer.ShuffleBufferManager.removeBufferByShuffleId(ShuffleBufferManager.java:656)
        at org.apache.uniffle.server.buffer.ShuffleBufferManager.removeBuffer(ShuffleBufferManager.java:319)
        at org.apache.uniffle.server.ShuffleTaskManager.removeResources(ShuffleTaskManager.java:757)
        at org.apache.uniffle.server.ShuffleTaskManager.lambda$new$0(ShuffleTaskManager.java:189)
        at java.lang.Thread.run(Thread.java:750)
```

Similar to https://github.com/apache/incubator-uniffle/issues/1542.

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rickyma** [comment]
Anyone will be welcome to pick this up.

**Comment by rickyma** [comment]
Done by https://github.com/apache/incubator-uniffle/pull/1574
