### ISSUE TITLE
[Bug] ConcurrentModificationException is thrown when calling Roaring64NavigableMap.getLongCardinality

### ISSUE THREAD

**Issue by rickyma** [apache/incubator-uniffle#1782]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

https://github.com/apache/incubator-uniffle/actions/runs/9381222136/job/25830065788?pr=1763

### Affects Version(s)

master

### Uniffle Server Log Output

```
[INFO] Running org.apache.uniffle.server.buffer.ShuffleBufferManagerTest
Error:  Tests run: 13, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.347 s <<< FAILURE! - in org.apache.uniffle.server.buffer.ShuffleBufferManagerTest
Error:  bufferSizeTest  Time elapsed: 0.646 s  <<< ERROR!
java.util.ConcurrentModificationException
	at java.util.TreeMap$NavigableSubMap$SubMapIterator.nextEntry(TreeMap.java:1703)
	at java.util.TreeMap$NavigableSubMap$SubMapEntryIterator.next(TreeMap.java:1751)
	at java.util.TreeMap$NavigableSubMap$SubMapEntryIterator.next(TreeMap.java:1745)
	at org.roaringbitmap.longlong.Roaring64NavigableMap.ensureCumulatives(Roaring64NavigableMap.java:553)
	at org.roaringbitmap.longlong.Roaring64NavigableMap.getLongCardinality(Roaring64NavigableMap.java:278)
	at org.apache.uniffle.server.buffer.ShuffleBufferManagerTest.waitForFlush(ShuffleBufferManagerTest.java:637)
	at org.apache.uniffle.server.buffer.ShuffleBufferManagerTest.bufferSizeTest(ShuffleBufferManagerTest.java:450)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maobaolong** [comment]
@rickyma After thinking about this issue and study `Roaring64NavigableMap`, I found that `Roaring64NavigableMap` is not thread-safe.

**Comment by rickyma** [comment]
> I suggest to use lock or clone to avoid race condition

Seems fine.

> we can use try catch to ignore this kind exception for testing

I think this is more of a hack than a fix.

**Comment by maobaolong** [comment]
> I think this is more of a hack than a fix.

I'm not sure how many days and how difficult to solve this issue. As it is for testing purpose, do you think a fail and retry could be a simple way to make the test passed?

As motioned, the `Roaring64NavigableMap` is not `thread-safe`, and it is not worth to add lock for production code only to make `test code` avoid race.

**Comment by rickyma** [comment]
You can refactor the test cases, or maybe just disable the tests.
