### ISSUE TITLE
[Bug] The dashboard does not start.

### ISSUE THREAD

**Issue by yl09099** [apache/incubator-uniffle#1895]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

#1852 Preconditions.checkArgument(coordinatorServerAddressesMap.isEmpty(), "No coordinator server address found.");
https://guava.dev/releases/19.0/api/docs/com/google/common/base/Preconditions.html
Reverse judgment.

Exception in thread "main" java.lang.IllegalArgumentException: No coordinator server address found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
	at org.apache.uniffle.dashboard.web.proxy.WebProxyServlet.<init>(WebProxyServlet.java:38)
	at org.apache.uniffle.dashboard.web.JettyServerFront.addProxyHandler(JettyServerFront.java:116)
	at org.apache.uniffle.dashboard.web.JettyServerFront.setRootServletHandler(JettyServerFront.java:100)
	at org.apache.uniffle.dashboard.web.JettyServerFront.initialization(JettyServerFront.java:87)
	at org.apache.uniffle.dashboard.web.JettyServerFront.<init>(JettyServerFront.java:64)
	at org.apache.uniffle.dashboard.web.JettyServerFront.main(JettyServerFront.java:76)

### Affects Version(s)

0.10.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yl09099** [comment]
@maobaolong @xianjingfeng @rickyma PATL

**Comment by maobaolong** [comment]
@yl09099 It's my fault, the condition is wrong, let me fixed it at once.
