### ISSUE TITLE
[Problem] Fail to init ClientConfManager,dynamic_client.conf is not a file

### ISSUE THREAD

**Issue by wfxxh** [apache/incubator-uniffle#224]
I edit the config file as README.

![image](https://user-images.githubusercontent.com/22764286/190567356-e32505c0-e126-4c46-a6cc-1a74f5c15fb4.png)

![image](https://user-images.githubusercontent.com/22764286/190567406-eedc2f0e-6563-4f51-bc0b-9765d368732c.png)

When I start the start Coordinator I get the error
![image](https://user-images.githubusercontent.com/22764286/190567578-35476e61-ee0a-4723-853a-902b0aac7dd4.png)

**Comment by wfxxh** [comment]
![image](https://user-images.githubusercontent.com/22764286/190569537-c6b14032-dfe8-4b8a-a292-4a228c37a6dc.png)

It shoud be a hdfs path not a local path

**Comment by jiangbiao910** [comment]
@wfxxh when I use a hdfs path，there log ：
`[INFO] 2022-10-13 11:00:54,868 main CoordinatorServer main - Start to init coordinator server using config /app/rss/rss/conf/coordinator.conf
[INFO] 2022-10-13 11:00:54,880 main RssUtils getPropertiesFromFile - Load config from /app/rss/rss/conf/coordinator.conf
[INFO] 2022-10-13 11:00:54,955 main CoordinatorServer registerMetrics - Register metrics
[INFO] 2022-10-13 11:00:55,000 main CoordinatorServer registerMetrics - Add metrics servlet
[WARN] 2022-10-13 11:00:55,971 main NativeCodeLoader <clinit> - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[INFO] 2022-10-13 11:00:56,225 main ApplicationManager refreshRemoteStorage - Refresh remote storage with hdfs:///tmp/path1,hdfs:///tmp/path2
[ERROR] 2022-10-13 11:00:56,227 main CoordinatorServer <init> - Errors on initializing coordinator server.
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at org.apache.uniffle.coordinator.ApplicationManager.getStorageHost(ApplicationManager.java:278)
        at org.apache.uniffle.coordinator.ApplicationManager.addRemoteStorageMetrics(ApplicationManager.java:263)
        at org.apache.uniffle.coordinator.ApplicationManager.refreshRemoteStorage(ApplicationManager.java:109)
        at org.apache.uniffle.coordinator.ClientConfManager.updateClientConfInternal(ClientConfManager.java:130)
        at org.apache.uniffle.coordinator.ClientConfManager.init(ClientConfManager.java:73)
        at org.apache.uniffle.coordinator.ClientConfManager.<init>(ClientConfManager.java:58)
        at org.apache.uniffle.coordinator.CoordinatorServer.initialization(CoordinatorServer.java:142)
        at org.apache.uniffle.coordinator.CoordinatorServer.<init>(CoordinatorServer.java:61)
        at org.apache.uniffle.coordinator.CoordinatorServer.main(CoordinatorServer.java:79)
`

**Comment by wfxxh** [comment]
@jiangbiao910 please show your config

**Comment by jiangbiao910** [comment]
@wfxxh thank you very much，
conf shoud be set  
rss.coordinator.remote.storage.path hdfs://nameservice1/tmp/path1,hdfs://nameservice1/tmp/path2
no 
rss.coordinator.remote.storage.path hdfs:///tmp/path1,hdfs:///tmp/path2
