### ISSUE TITLE
[Flaky Test] Throw an  io.netty.util.IllegalReferenceCountException

### ISSUE THREAD

**Issue by roryqi** [apache/incubator-uniffle#2273]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1383)
	at io.netty.buffer.PooledByteBuf.duplicateInternalNioBuffer(PooledByteBuf.java:196)
	at io.netty.buffer.PooledByteBuf.nioBuffer(PooledByteBuf.java:213)
	at io.netty.buffer.AbstractByteBuf.nioBuffer(AbstractByteBuf.java:1231)
	at org.apache.uniffle.common.netty.buffer.NettyManagedBuffer.nioByteBuffer(NettyManagedBuffer.java:48)
	at org.apache.uniffle.common.ShuffleIndexResult.getIndexData(ShuffleIndexResult.java:84)

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/12158115239/attempts/1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
Maybe we shouldn't use PooledByteBuf. Because we will release the memory after we used the memory. You can see https://github.com/apache/incubator-uniffle/blob/28475fced12f5a4b79152d146ead1917982f44b9/storage/src/main/java/org/apache/uniffle/storage/handler/impl/DataSkippableReadHandler.java#L82

cc @advancedxy @rickyma WDYT?

**Comment by jerqi** [comment]
> Users can choose whatever kind of bytebuf they want: client: #1767 server: #2145
> 
> We basically will release every bytebuf, but it does not mean that we don't need PooledByteBuf. We use PooledByteBuf to reduce the number of interactions with the operating system for memory allocation and deallocation. This helps to avoid potential issues such as abnormal growth of RSS (Resident Set Size) memory, which might occur due to frequent and inefficient memory management (especially when using glibc, that's why we recommend using [mimalloc](https://github.com/apache/incubator-uniffle/blob/master/docs/server_guide.md#malloc-recommendation)).

But it will throw a ref count exception. I suspect that we released a reused bytebuf in the ByteBuf pool.

**Comment by jerqi** [comment]
I suspect that the issue is caused by `TransportFrameDecoder`
```
  @Override
  public void handlerRemoved(ChannelHandlerContext ctx) throws Exception {
    // Release all buffers that are still in our ownership.
    // Doing this in handlerRemoved(...) guarantees that this will happen in all cases:
    //     - When the Channel becomes inactive
    //     - When the decoder is removed from the ChannelPipeline
    for (ByteBuf b : buffers) {
      b.release();
    }
    buffers.clear();
    headerBuf.release();
    super.handlerRemoved(ctx);
  }
```
