### ISSUE TITLE
Flaky Test: AppBalanceSelectStorageStrategyTest#selectStorageTest

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#430]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.293 s <<< FAILURE! - in org.apache.uniffle.coordinator.strategy.storage.AppBalanceSelectStorageStrategyTest
Error:  selectStorageTest  Time elapsed: 2.038 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <hdfs://path2> but was: <hdfs://path1>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at org.apache.uniffle.coordinator.strategy.storage.AppBalanceSelectStorageStrategyTest.selectStorageTest(AppBalanceSelectStorageStrategyTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/3710032877/jobs/6289187657

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
PTAL @smallzhongfeng . Thanks~

**Comment by smallzhongfeng** [comment]
Where can I see logs printed? I remember that @jerqi can collect some logs before. @zuston

**Comment by smallzhongfeng** [comment]
I read the code. I think it is when the `detectStorageScheduler` reads and writes the hdfs file `hdfs://path2 `An exception occurred, which caused the `AppBalanceSelectStorageStrategy.pickStorage` to filter `hdfs://path2`

**Comment by zuston** [comment]
> https://github.com/apache/incubator-uniffle/actions/runs/3710032877/jobs/6289187657

You could get the output log from https://github.com/apache/incubator-uniffle/suites/9900991081/artifacts/478415001.

**Comment by zuston** [comment]
> I read the code. I think it is when the `detectStorageScheduler` reads and writes the hdfs file `hdfs://path2 `An exception occurred, which caused the `AppBalanceSelectStorageStrategy.pickStorage` to filter `hdfs://path2`

Could you help fix this?

**Comment by smallzhongfeng** [comment]
2022-12-16 03:33:48,729 ERROR [detectStoragesScheduler-0] storage.AppBalanceSelectStorageStrategy (AppBalanceSelectStorageStrategy.java:detectStorage(99)) - Storage read and write error, we will not use this remote path hdfs://path2=RankValue{costTime=9223372036854775807, appNum=0, isHealthy=false}.

**Comment by smallzhongfeng** [comment]
> > I read the code. I think it is when the `detectStorageScheduler` reads and writes the hdfs file `hdfs://path2 `An exception occurred, which caused the `AppBalanceSelectStorageStrategy.pickStorage` to filter `hdfs://path2`
> 
> Could you help fix this?

Yes, I will fix it.

**Comment by zuston** [comment]
Solved by https://github.com/apache/incubator-uniffle/pull/438

**Comment by zuston** [comment]
This bug still exist. 

https://github.com/apache/incubator-uniffle/actions/runs/3747690721/jobs/6364186080

**Comment by smallzhongfeng** [comment]
> https://github.com/apache/incubator-uniffle/suites/9900991081/artifacts/478415001.

Could  you tell me how to get the log of a test? @zuston
