### ISSUE TITLE
Flaky Test: QuotaManagerTest#testDetectUserResource

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#442]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.614 s <<< FAILURE! - in org.apache.uniffle.coordinator.QuotaManagerTest
Error:  testDetectUserResource  Time elapsed: 1.57 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <null> but was: <30>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:541)
	at org.apache.uniffle.coordinator.QuotaManagerTest.testDetectUserResource(QuotaManagerTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/3746246955/jobs/6361411867

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by smallzhongfeng** [comment]
Could you tell me how to get the log of a test?  I need fix this. @zuston

**Comment by zuston** [comment]
Follow these steps:
1. Click the url of https://github.com/apache/incubator-uniffle/actions/runs/3746246955/jobs/6361411867
2. Click the button of summary, it will render to the summary page
3. Find the Artifacts, and then download it.

**Comment by smallzhongfeng** [comment]
> Follow these steps:
> 
> 1. Click the url of https://github.com/apache/incubator-uniffle/actions/runs/3746246955/jobs/6361411867
> 2. Click the button of summary, it will render to the summary page
> 3. Find the Artifacts, and then download it.

Great! Thanks a lot.

**Comment by smallzhongfeng** [comment]
`org.opentest4j.AssertionFailedError: expected: <null> but was: <30>` 
It is said here that the expectation is null, but it is actually 30. However, the expected value of my code is 30. I feel a little confused
```
assertEquals(user3, 30);
```

**Comment by smallzhongfeng** [comment]
@jerqi @zuston At present, it seems that this is not the problem of the code I wrote. WDYT?

**Comment by jerqi** [comment]
> `org.opentest4j.AssertionFailedError: expected: <null> but was: <30>` It is said here that the expectation is null, but it is actually 30. However, the expected value of my code is 30. I feel a little confused
> 
> ```
> assertEquals(user3, 30);
> ```

user3 is set null value.

**Comment by smallzhongfeng** [comment]
> > `org.opentest4j.AssertionFailedError: expected: <null> but was: <30>` It is said here that the expectation is null, but it is actually 30. However, the expected value of my code is 30. I feel a little confused
> > ```
> > assertEquals(user3, 30);
> > ```
> 
> user3 is set null value.
```
2022-12-21 03:52:53,270 ERROR [UpdateDefaultApp-0] coordinator.QuotaManager (QuotaManager.java:detectUserResource(94)) - Can't find this file hdfs://localhost:40055/quotaFile.properties
```
This is the reason why user3 is null, because the update of quota file failed. I'll fix this.

**Comment by smallzhongfeng** [comment]
> > `org.opentest4j.AssertionFailedError: expected: <null> but was: <30>` It is said here that the expectation is null, but it is actually 30. However, the expected value of my code is 30. I feel a little confused
> > ```
> > assertEquals(user3, 30);
> > ```
> 
> user3 is set null value.
```
2022-12-21 03:52:53,270 ERROR [UpdateDefaultApp-0] coordinator.QuotaManager (QuotaManager.java:detectUserResource(94)) - Can't find this file hdfs://localhost:40055/quotaFile.properties
```
This is the reason why user3 is null, because the update of quota file failed. I'll fix this.
