### ISSUE TITLE
Flaky Test: LocalFileServerReadHandlerTest#testDataInconsistent

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#472]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.862 s <<< FAILURE! - in org.apache.uniffle.storage.handler.impl.LocalFileServerReadHandlerTest
Error:  testDataInconsistent  Time elapsed: 1.861 s  <<< ERROR!
java.lang.NullPointerException
	at org.apache.uniffle.storage.handler.impl.LocalFileHandlerTestBase.calcSegmentBytes(LocalFileHandlerTestBase.java:139)
	at org.apache.uniffle.storage.handler.impl.LocalFileServerReadHandlerTest.testDataInconsistent(LocalFileServerReadHandlerTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/3891086394/jobs/6640903029

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kaijchen** [comment]
This is due to `LocalFileHandlerTest` and `LocalFileServerReadHandlerTest` sharing a common state in `LocalFileHandlerTestBase#ATOMIC_LONG`
