### ISSUE TITLE
Flaky Test: ShuffleServerFaultToleranceTest#testReadFaultTolerance

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#483]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.929 s <<< FAILURE! - in org.apache.uniffle.test.ShuffleServerFaultToleranceTest
Error:  testReadFaultTolerance  Time elapsed: 0.152 s  <<< ERROR!
java.lang.NullPointerException
	at org.apache.uniffle.client.TestUtils.validateResult(TestUtils.java:66)
	at org.apache.uniffle.test.ShuffleServerFaultToleranceTest.testReadFaultTolerance(ShuffleServerFaultToleranceTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/3908347548/jobs/6678420762

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kaijchen** [comment]
It's weird that this test fails so often in CI.
https://github.com/apache/incubator-uniffle/actions/runs/3928645075

But It's hard to reproduce it locally.
<img width="783" alt="image" src="https://user-images.githubusercontent.com/5821159/212640922-bca848b6-da75-4faa-8b78-2fd545008991.png">

**Comment by zuston** [comment]
Could you help fix this? @smallzhongfeng
