### ISSUE TITLE
Flaky Test: QuorumTest#case5

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#502]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
[INFO] Running org.apache.uniffle.test.AccessCandidatesCheckerHdfsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.841 s - in org.apache.uniffle.test.AccessCandidatesCheckerHdfsTest
[INFO] Running org.apache.uniffle.test.CoordinatorGrpcTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.744 s - in org.apache.uniffle.test.CoordinatorGrpcTest
[INFO] Running org.apache.uniffle.test.ShuffleServerConcurrentWriteOfHdfsTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.722 s - in org.apache.uniffle.test.ShuffleServerConcurrentWriteOfHdfsTest
[INFO] Running org.apache.uniffle.test.ShuffleServerWithHdfsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.363 s - in org.apache.uniffle.test.ShuffleServerWithHdfsTest
[INFO] Running org.apache.uniffle.test.ShuffleWithRssClientTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 75.436 s - in org.apache.uniffle.test.ShuffleWithRssClientTest
[INFO] Running org.apache.uniffle.test.DiskErrorToleranceTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.069 s - in org.apache.uniffle.test.DiskErrorToleranceTest
[INFO] Running org.apache.uniffle.test.ShuffleServerGrpcTest
Warning:  Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 26.458 s - in org.apache.uniffle.test.ShuffleServerGrpcTest
[INFO] Running org.apache.uniffle.test.QuorumTest
Error:  Tests run: 14, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 66.687 s <<< FAILURE! - in org.apache.uniffle.test.QuorumTest
Error:  case5{File}  Time elapsed: 2.658 s  <<< ERROR!
org.apache.uniffle.common.exception.RssException: Get shuffle result is failed for appId[case5], shuffleId[0]
	at org.apache.uniffle.client.impl.ShuffleWriteClientImpl.getShuffleResult(ShuffleWriteClientImpl.java:550)
	at org.apache.uniffle.test.QuorumTest.case5(QuorumTest.java:502)
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/3954858017/jobs/6772624759

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment]
This pr's test failed. https://github.com/apache/incubator-uniffle/actions/runs/3954858017 cc @kaijchen

**Comment by kaijchen** [comment]
@zuston thanks for reporting this issue. I'm not sure what's happened, have you seen this failure before #492?
<img width="768" alt="100x QuorumTest#case5" src="https://user-images.githubusercontent.com/5821159/213349218-d9239a28-3518-4cc2-9bfb-eec0dfdf1dd7.png">
