### ISSUE TITLE
Flaky Test: LowestIOSampleCostSelectStorageStrategyTest#selectStorageTest

### ISSUE THREAD

**Issue by kaijchen** [apache/incubator-uniffle#526]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 19.844 s <<< FAILURE! - in org.apache.uniffle.coordinator.strategy.storage.LowestIOSampleCostSelectStorageStrategyTest
Error:  selectStorageTest  Time elapsed: 7.611 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <hdfs://p2> but was: <hdfs://p1>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at org.apache.uniffle.coordinator.strategy.storage.LowestIOSampleCostSelectStorageStrategyTest.selectStorageTest(LowestIOSampleCostSelectStorageStrategyTest.java:138)
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/4043459641/jobs/6952402959#step:6:2486

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
cc. @smallzhongfeng

**Comment by smallzhongfeng** [comment]
Thanks ping me. I will fix this.
