### ISSUE TITLE
Flaky Test: RssShuffleWriterTest#writeTest

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#610]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
Error:  Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 17.413 s <<< FAILURE! - in org.apache.spark.shuffle.writer.RssShuffleWriterTest
Error:  writeTest  Time elapsed: 2.387 s  <<< ERROR!
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1493)
	at java.util.AbstractSet.removeAll(AbstractSet.java:174)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.checkBlockSendResult(RssShuffleWriter.java:303)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.checkBlockSendResult(RssShuffleWriter.java:289)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.writeImpl(RssShuffleWriter.java:194)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    RssShuffleWriterTest.writeTest » ConcurrentModification
[INFO] 
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/4191190002/jobs/7265371289

### Parent issue

#1733

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by kaijchen** [comment]
Tip: We have enabled `mvn -T1C` in CI. Maybe it's due to some shared static objects.

**Comment by zuston** [comment]
Yes. Maybe it uses the same sparkContext

**Comment by kaijchen** [comment]
If it is hard to fix and fails often, we can revert the `-T1C` option.

**Comment by zuston** [comment]
OK

**Comment by zuston** [comment]
> If it is hard to fix and fails often, we can revert the `-T1C` option.

This has been reverted, let's close this. cc @kaijchen
