### ISSUE TITLE
[Flaky Test] CoordinatorMetricsTest#testCoordinatorMetrics  

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#691]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.421 s <<< FAILURE! - in org.apache.uniffle.coordinator.metric.CoordinatorMetricsTest
Error:  testCoordinatorMetrics  Time elapsed: 0.019 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <10> but was: <12>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)
	at org.apache.uniffle.coordinator.metric.CoordinatorMetricsTest.testCoordinatorMetrics(CoordinatorMetricsTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/4354707689/jobs/7610349067

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by smallzhongfeng** [comment]
This may be caused by the added indicators of 
```
app_num{user_name="user3",} 1.0
app_num{user_name="user4",} 2.0
```
Here I think quota should be turned off first in the indicator detection ut.

**Comment by smallzhongfeng** [comment]
Let me fix it. : -)
