### ISSUE TITLE
[Flaky Test] ShuffleServerFaultToleranceTest#testReadFaultTolerance

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/incubator-uniffle#701]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.014 s <<< FAILURE! - in org.apache.uniffle.test.ShuffleServerFaultToleranceTest
Error:  testReadFaultTolerance  Time elapsed: 0.222 s  <<< ERROR!
java.lang.NullPointerException
	at org.apache.uniffle.client.TestUtils.validateResult(TestUtils.java:66)
	at org.apache.uniffle.test.ShuffleServerFaultToleranceTest.testReadFaultTolerance(ShuffleServerFaultToleranceTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:[725](https://github.com/apache/incubator-uniffle/actions/runs/4370690355/jobs/7645845268#step:6:726))
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at
```

### Actions URL

https://github.com/apache/incubator-uniffle/actions/runs/4370690355/jobs/7645845268

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by smallzhongfeng** [comment]
This ut failure occurs frequently. PTAL @jerqi @kaijchen

**Comment by kaijchen** [comment]
duplicated with #483, closing this.
