### ISSUE TITLE
[Flaky Test] ShuffleServerMetricsTest#testServerMetrics

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/incubator-uniffle#809]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the flaky test

When run
```
mvn clean test -Pspark3.2
mvn clean test -Pspark2
```
it would cause
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.31 s <<< FAILURE! - in org.apache.uniffle.server.ShuffleServerMetricsTest
[ERROR] testServerMetrics  Time elapsed: 0.225 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: array contents differ at index [1], expected: <hdfs1> but was: <localhost>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
        at org.junit.jupiter.api.AssertArrayEquals.failArraysNotEqual(AssertArrayEquals.java:432)
        at org.junit.jupiter.api.AssertArrayEquals.assertArrayElementsEqual(AssertArrayEquals.java:392)
        at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:349)
        at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:162)
        at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:158)
        at org.junit.jupiter.api.Assertions.assertArrayEquals(Assertions.java:1452)
        at org.apache.uniffle.server.ShuffleServerMetricsTest.validateMetrics(ShuffleServerMetricsTest.java:119)
        at org.apache.uniffle.server.ShuffleServerMetricsTest.testServerMetrics(ShuffleServerMetricsTest.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

### Actions URL

Running `mvn clean test - Pspark2` locally will replicate

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by smallzhongfeng** [comment]
cc @advancedxy it seems occur after #799
