### ISSUE TITLE
[Bug] Uniffle shuffle server failing to start

### ISSUE THREAD

**Issue by fhalde** [apache/incubator-uniffle#946]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

I was trying out uniffle locally and we face the following error when starting the shuffle server

```
[ERROR] 2023-06-12 16:32:19,896 main ShuffleServer <init> - Errors on initializing shuffle server.
org.apache.uniffle.common.exception.RssException: Initialize 1 local storage(s) failed, specified local storage paths size: 1, the conf of rss.server.localstorage.initialize.max.fail.number size: 0
	at org.apache.uniffle.server.storage.LocalStorageManager.<init>(LocalStorageManager.java:147)
	at org.apache.uniffle.server.storage.StorageManagerFactory.createStorageManager(StorageManagerFactory.java:36)
	at org.apache.uniffle.server.ShuffleServer.initialization(ShuffleServer.java:222)
	at org.apache.uniffle.server.ShuffleServer.<init>(ShuffleServer.java:103)
	at org.apache.uniffle.server.ShuffleServer.main(ShuffleServer.java:121)
```

uniffle was built using
```
./build_distribution.sh --spark3-profile 'spark3.3'
```
jvm used: 1.8

coordinator.conf
```
rss.rpc.server.port 19999
rss.jetty.http.port 19998
rss.coordinator.server.heartbeat.timeout 30000
rss.coordinator.app.expired 60000
rss.coordinator.shuffle.nodes.max 13
```

server.conf
```
rss.rpc.server.port 19989
rss.jetty.http.port 19988
rss.storage.basePath /tmp
rss.storage.type MEMORY_LOCALFILE
rss.coordinator.quorum 127.0.0.1:19999
rss.server.buffer.capacity 2gb
rss.server.read.buffer.capacity 2gb
rss.server.flush.thread.alive 5
rss.server.flush.threadPool.size 10
rss.server.disk.capacity -1
```

rss-env.sh
```
set -o pipefail
set -o nounset   # exit the script if you try to use an uninitialised variable
set -o errexit   # exit the script if any statement returns a non-true return value

JAVA_HOME=<java path>
HADOOP_HOME=/tmp/hadoop-3.3.5
XMX_SIZE="1g" # Shuffle Server JVM XMX size

RSS_IP=127.0.0.1
```

### Affects Version(s)

master

### Uniffle Server Log Output

```logtalk
[INFO] 2023-06-12 16:32:19,729 main ShuffleServer main - Start to init shuffle server using config /Users/faiz.halde/dev/nu/nucli/incubator-uniffle/rss-0.8.0-SNAPSHOT/conf/server.conf
[INFO] 2023-06-12 16:32:19,738 main RssUtils getPropertiesFromFile - Load config from /Users/faiz.halde/dev/nu/nucli/incubator-uniffle/rss-0.8.0-SNAPSHOT/conf/server.conf
[INFO] 2023-06-12 16:32:19,780 main ShuffleServer registerMetrics - Register metrics
[INFO] 2023-06-12 16:32:19,805 main ShuffleServer registerMetrics - Add metrics servlet
[ERROR] 2023-06-12 16:32:19,896 main ShuffleServer <init> - Errors on initializing shuffle server.
org.apache.uniffle.common.exception.RssException: Initialize 1 local storage(s) failed, specified local storage paths size: 1, the conf of rss.server.localstorage.initialize.max.fail.number size: 0
	at org.apache.uniffle.server.storage.LocalStorageManager.<init>(LocalStorageManager.java:147)
	at org.apache.uniffle.server.storage.StorageManagerFactory.createStorageManager(StorageManagerFactory.java:36)
	at org.apache.uniffle.server.ShuffleServer.initialization(ShuffleServer.java:222)
	at org.apache.uniffle.server.ShuffleServer.<init>(ShuffleServer.java:103)
	at org.apache.uniffle.server.ShuffleServer.main(ShuffleServer.java:121)
```

### Uniffle Server Configurations

```yaml
rss.rpc.server.port 19989
rss.jetty.http.port 19988
rss.storage.basePath /tmp
rss.storage.type MEMORY_LOCALFILE
rss.coordinator.quorum 127.0.0.1:19999
rss.server.buffer.capacity 2gb
rss.server.read.buffer.capacity 2gb
rss.server.flush.thread.alive 5
rss.server.flush.threadPool.size 10
rss.server.disk.capacity -1
```

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jerqi** [comment]
Could we paste more logs
<img width="558" alt="企业微信截图_460e9376-4933-4eb0-b400-5c85023ac9b8" src="https://github.com/apache/incubator-uniffle/assets/8159038/a13c5bca-82a1-471c-9d88-52301acc7dfb">

**Comment by fhalde** [comment]
yes, so i did that. it does enter the try statement but never reaches the `successCount.incrementAndGet();` statement

what's strange is an error should've been caught in the catch statement and I should've seen the "LocalStorage init failed!" error but nothing was printed

**Comment by fhalde** [comment]
what other logs should I put?

**Comment by fhalde** [comment]
ahan, found it. it was indeed throwing a Error not an Exception

```
[ERROR] 2023-06-13 10:22:19,983 LocalStorage-check-0 LocalStorageManager lambda$new$0 - LocalStorage init failed!
java.lang.NoClassDefFoundError: org/apache/commons/lang/SystemUtils
	at org.apache.uniffle.storage.common.DefaultStorageMediaProvider.getStorageMediaFor(DefaultStorageMediaProvider.java:59)
	at org.apache.uniffle.server.storage.LocalStorageManager.getStorageTypeForBasePath(LocalStorageManager.java:168)
	at org.apache.uniffle.server.storage.LocalStorageManager.lambda$new$0(LocalStorageManager.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.SystemUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more
```

**Comment by fhalde** [comment]
but i'm not entirely sure how to fix this. i don't see org.apache.commons as a provided dependency ( sorry but i am not well versed with maven )

**Comment by fhalde** [comment]
`DefaultStorageMediaProvider` uses
`import org.apache.commons.lang.SystemUtils;`. should it have been `import org.apache.commons.lang3.SystemUtils;` ?

**Comment by fhalde** [comment]
but then the question is, why did it compile?

**Comment by jerqi** [comment]
@fhalde After https://github.com/apache/incubator-uniffle/pull/897, we should fix this issue.

**Comment by fhalde** [comment]
worked with latest master
